pass-original-item-name-to-resource-packs: true
always-show-original-mob-name: true
add-custom-enchants-into-lore: true
add-teamcolor-to-prefix: true
fix-1_13-face-player: false
fix-formatted-inventory-titles: true
handle-pings-as-inv-acknowledgements: false
bedrock-at-y-0: false
sculk-shriekers-to-crying-obsidian: true
scaffolding-to-water: false
map-darkness-effect: true
map-custom-model-data: true
map-display-entities: true
suppress-emulation-warnings: false
dialogs-via-chests: true
code-of-conduct-as-dialog: true
