# Vupe MAX starting point. Minehut/panel settings may override some values.
motd=Vupe MAX
max-players=100
view-distance=10
simulation-distance=8
spawn-protection=0
allow-flight=true
pvp=true
difficulty=normal
white-list=true
allow-nether=true
network-compression-threshold=256
enable-command-block=false
